#!/usr/bin/env node
/**
 * write-version.mjs — version single-sourcing (v1.9.0, plan item M2).
 *
 * Reads package.json and (re)writes src/generated/appVersion.ts so the
 * backend bundle, the vite frontend and any packaged artifact share ONE
 * version constant without runtime package.json lookups (which break in
 * installed apps where package.json is not next to the bundle).
 *
 * Runs automatically in `npm run build` (prestep). Idempotent: only
 * touches the file when the version actually changes, so it never
 * invalidates vite/esbuild caches on unrelated builds.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const pkgPath = path.join(here, '..', 'package.json');
const outPath = path.join(here, '..', 'src', 'generated', 'appVersion.ts');

const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8'));
const version = String(pkg.version || '0.0.0');
if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`[write-version] package.json version "${version}" is not semver-like — aborting.`);
  process.exit(1);
}

const content =
  `// GENERATED by scripts/write-version.mjs from package.json — do not edit.\n` +
  `// Regenerated automatically on every build; single source of truth.\n` +
  `export const APP_VERSION = '${version}';\n`;

const existing = fs.existsSync(outPath) ? fs.readFileSync(outPath, 'utf8') : null;
if (existing !== content) {
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`[write-version] src/generated/appVersion.ts → ${version}`);
} else {
  console.log(`[write-version] ${version} (unchanged)`);
}
